version: '3.8'

services:
  data-sentinel:
    build: .
    ports:
      - "8000:8000"  # FastAPI
      - "8501:8501"  # Streamlit
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=sqlite:////app/data/sentinel.db
      - DW_CONN_STRING=sqlite:///./data/dw.db
      - LLM_PROVIDER=groq
      # - LLM_API_KEY=REMOVED
      # - SECRET_KEY=your-secret-key-change-this-in-production
      - DEBUG=True
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s